# Generated by Django 3.1.1 on 2020-09-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('addres', models.CharField(max_length=250, verbose_name='Адрес')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Список Библиотек',
                'verbose_name_plural': 'Список библиотек',
            },
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Список литературы', 'verbose_name_plural': 'Список литературы'},
        ),
    ]
