# Generated by Django 3.1.2 on 2020-11-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
