# Generated by Django 3.1.2 on 2020-12-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customers_middle_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarian',
            options={'verbose_name': 'Библиотекарь', 'verbose_name_plural': 'Список библиотекарей'},
        ),
    ]
