# Generated by Django 3.1.2 on 2020-12-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201202_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='number',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customers',
            name='residence',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
