# Generated by Django 3.1.2 on 2020-12-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20201123_1157'),
        ('accounts', '0008_customers_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='books',
        ),
        migrations.AddField(
            model_name='customers',
            name='books',
            field=models.ManyToManyField(null=True, to='list.Articles'),
        ),
    ]
